### ISSUE TITLE
Add support for Lex and Polly APIs

### ISSUE THREAD

**Issue by justinmoon** [awslabs/aws-sdk-react-native#31]
Support functionality demonstrated in [awslabs/aws-sdk-ios-samples](https://github.com/awslabs/aws-sdk-ios-samples#amazon-lex-sample-objc-swift23-swift3) and [awslabs/aws-sdk-android-samples](https://github.com/awslabs/aws-sdk-ios-samples#amazon-lex-sample-objc-swift23-swift3).

Thanks!

**Comment by TylerM89** [comment]
Been over a year since this was created. Would really love to see support for these products.

**Comment by thecloudslayer** [comment]
Has anyone see anything like this https://docs.aws.amazon.com/aws-mobile/latest/developerguide/add-aws-mobile-conversational-bots.html for react native?

**Comment by bharloe** [comment]
@thecloudslayer Have you seen this? https://medium.com/@itsHabib/integrate-an-amazon-lex-chatbot-into-a-react-native-app-1536883ccbed

**Comment by ohtangza** [comment]
Any progress on this?

**Comment by EricPKerr** [comment]
@awslabs @justinmoon has there been any update to using Polly or Lex with this SDK?

**Comment by justinmoon** [comment]
I gave up shortly after posting this issue. They don't seem too responsive ...

**Comment by undefobj** [comment]
@EricPKerr @justinmoon please take a look at the AWS Amplify library which we released for React Native development:

https://aws-amplify.github.io
https://github.com/aws-amplify/amplify-js

It might have been missed but in the top of the README we noted that this is the recommended library to use rather than this developer preview.
