### ISSUE TITLE
Amazon Rekognition

### ISSUE THREAD

**Issue by hugohow** [awslabs/aws-sdk-react-native#57]
Hello, 
Is it possible to access to Amazon Rekognition with this library ?

Thanks

**Comment by shrinandhini2801** [comment]
Can some one say this?

**Comment by dsummersl** [comment]
It can be done - here is a branch that I got to a sufficient point that I could use what methods I wanted: https://github.com/awslabs/aws-sdk-react-native/compare/master...dsummersl:rekognition_support?expand=1

I didn't end up making a PR because I didn't get around to writing test cases (and this was only  Android support)
